version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SlackDoorBell"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1obvzsi4bj63y"
s3_prefix = "SlackDoorBell"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

